name: Workflow Test

on:
  workflow_call:
    outputs:
      echoed-value:
        description: 'The value echoed by the action'
        value: ${{ jobs.echostuff.outputs.echoed }}

jobs:
  # test action works running from the graph  
  echostuff:
    name: Echo Stuff
    outputs:
      echoed: ${{ steps.final_echo.outputs.echoed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo stuff
        id: final_echo
        shell: pwsh
        run: |
          "echoed=timvaluehuer" >> $env:GITHUB_OUTPUT

      - name: echo output
        run: |
          echo "echoed: ${{ steps.final_echo.outputs.echoed }}"
