name: Workflow Test

on: 
  workflow_call:
    outputs:
      echoed: ${{ jobs.echostuff.outputs.echoed }}

jobs:
  # test action works running from the graph  
  echostuff:
    outputs:
      echoed: ${{ steps.final_echo.outputs.echoed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo stuff
        id: final_echo
        run: |
          echo "echoed=timvaluehuer" >> "$GITHUB_OUTPUT"

      - name: echo output
        run: |
          echo "echoed: ${{ steps.final_echo.outputs.echoed }}"
