name: "Consumer"

on: workflow_dispatch
      
permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/_core.yml

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    env:
        ECHOED_VAL: ${{ needs.build.outputs.echoed }}

    steps:
    - name: Echoed value
      run: |
          echo "The value from output: ${{ env.ECHOED_VAL }}"
