name: "Maui macos"

on: workflow_dispatch
      
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: install maui
        shell: pwsh
        run: |
          dotnet nuget locals all --clear
          dotnet workload update
          dotnet workload install maui macos ios wasm-tools
