name: "Matrix and Outputs"

on: workflow_dispatch
      
permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_one: ${{ steps.step1.outputs.output_one }}
    
    steps:
      - id: step1
        name: Step 1
        run: |
          json_string="[{\"name\":\"customerprofiles\"},{\"name\":\"basket\"},{\"name\":\"orderprocessor\"},{\"name\":\"catalog\"},{\"name\":\"frontend\"}]"
          echo "output_one=$json_string" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        output_one: ${{ fromJson(needs.job1.outputs.output_one) }}
    steps:
      - name: Step 2
        run: |
          echo "Name=${{ matrix.output_one.name }}"