name: Local Test

on: [workflow_dispatch, workflow_call,push]

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Write file (1)
      id: write_file
      uses: timheuer/base64-to-file@main
      with:
        fileName: 'stuff/myTemporaryFile.txt'
        encodedString: 'SGVsbG8sIFdvcmxkIQ==' #${{ secrets.SOME_ENCODED_STRING }} # SGVsbG8sIFdvcmxkIQ==
