name: Workflow Test

on: [workflow_dispatch, workflow_call]

jobs:
  # test action works running from the graph  
  decode_file:
    name: Decode file
    uses: timheuer/base64-to-file/.github/workflows/another-workflow.yml@testing
