name: Workflow Test

on: [workflow_dispatch, workflow_call,push]

jobs:
  # test action works running from the graph  
  decode_file:
    name: Decode file
    uses: timheuer/workflow-playground/.github/workflows/workflow1.yml@main